### ISSUE TITLE
Add support for "author" and "text" styles

### ISSUE THREAD

**Issue by bdarcus** [andras-simonyi/citeproc-el#15]
With the announcement of `oc-csl`, it seems this package is where the focus should be (and would be anyway for new styles support).

Of note: if you add support for the "author" style, it's a small step to "text" too, which is just "author/bare" + "suppress author" (which you already support).

**Comment by andras-simonyi** [comment]
> With the announcement of oc-csl, it seems this package is where the focus should be (and would be anyway for new styles support).

Yes, especially if org-ref switches to the new org citation syntax from the current cite links.

**Comment by andras-simonyi** [comment]
Looking at the proposed list of citation styles on the [bibtex-actions](https://github.com/bdarcus/bibtex-actions/wiki/Org-cite) wiki I'm wondering how they should behave when there are several cites. Should they always affect only the first cite?

**Comment by bdarcus** [comment]
> Looking at the proposed list of citation styles on the bibtex-actions org-cite wiki page I'm wondering how they should behave when there are several cites. Should they always affect only the first cite?

I'm sure some details will need to be sorted out, an d so tentative thoughts.

I think you already concluded how to handle suppress author; that it would only effect the author of the first cite.

E.g. if you have `[cite/noauthor:doe19;doe20;jones21]`, you would have something like:

``` 
(2019, 2020; Jones 2021)
```

... and so because `text` is `author` + `noauthor`, it would apply there too.

Are there other styles you're concerned about?

> Also a specific question regarding the year style: should the output contain the year suffix if present?

Am not sure; I would follow natbib and biblatex?

@denismaier - any input on this?

**Comment by andras-simonyi** [comment]
> Are there other styles you're concerned about?

Well I'm trying to formulate the needed transformations (acting on the default rendering). I suppose the `author`, `year` and maybe even the `title` styles should handle cases when a different, but similar variable is rendered by the default style, e.g., `editor' instead of `author`. WDYT?


> > Also a specific question regarding the year style: should the output contain the year suffix if present?
> 
> Am not sure; I would follow natbib and biblatex?
> 
> @denismaier - any input on this?

**Comment by bdarcus** [comment]
Am not super sure, but I would test and see what happens with, in
particular, biblatex.

It's very well designed in general, and I'm sure they've tackled these
questions.

Since the OC style mappings are designed to be portable across output
backends, this should be easy.

We may need to propose amendments to the CSL spec based on what we conclude.

**Comment by andras-simonyi** [comment]
I've tested the behavior of biblatex with citeauthor plus read the corresponding part in the manual and I think the output is any (single) rendered name variable, not only the author, which is fairly reasonable IMHO.

**Comment by andras-simonyi** [comment]
Thinking about the `title` variant I ran into a problem: where would the precise formatting come from? It could easily print out simply the field's content of course, but I guess the point is to add some style-based rich-text markup as well. Cf. the difference between `citetitle` and `citefield` in biblatex: the first adds style-based markup, the second not.  The problem is, in a sense, very general: as long as the only citation markup information in a CSL style is about the default citation formatting, all other citation substyles are hacks to somehow infer the correct formatting for other settings. Since something like `author` and `year` is almost always present, at least for author-date styles, these formattings can be inferred, but this is not the case for `title', among others.

**Comment by bdarcus** [comment]
> The cleanest solution, of course, would be adding independent elements describing all the possible substyles, in the same way as it's planned for text citations IIUC.

You mean in CSL; right?

It's something we could consider. If you conclude we need it, can you add the issue to our schema tracker?

But I think for now, either don't support title, or just print the content without styling?

If the latter, could maybe have a `citeproc-title-style` variable for a user, say, that wants them italicized?

**Comment by bwiernik** [comment]
I'm not following. If you mean the 'title' CSL variable, styling of that is provided in regular CSL style in cs:intext.

**Comment by bdarcus** [comment]
> I'm not following. If you mean the 'title' CSL variable, styling of that is provided in regular CSL style in cs:intext.

@andras-simonyi is looking to implement a "title only" citation style (like biblatex `\citetitle`), and so was pointing out it's not clear how he should format that variable in that context.

So I was wondering if `cs:intext` needed to be generalized to allow that (and not remembering if we ever talked about this specifically).

Minimal strawman for illustration:

``` xml
<cs:intext foo="title">
...
</cs:intext>
```

... or maybe more general still:

``` xml
<cs:alternative foo="title">
...
</cs:cs:alternative>
<cs:alternative foo="author-in-text">
...
</cs:cs:alternative>
```

Is something like that WYM @andras-simonyi?

**Comment by bwiernik** [comment]
Okay, can you explain what the context for this would be? What is the use for this versus a cs:intext, which is designed as a generic "any in text component". You could in a style simply set cs:intext to render the title variable (or eg, show authors for journal articles, but titles for legislation)

**Comment by bdarcus** [comment]
This isn't global citation rendering; it's citation-specific variant styles.

So one may want one citation to have a "text" style, and another to have a
"title" style.

Here's a table that gives some context.

https://github.com/bdarcus/bibtex-actions/wiki/Org-cite

He's basically figuring out what styles and variants to support, and how.

As I've suggested to him, though, this isn't the most important style to
support, and it would be fine if he didn't.

But it raised the broader question for me.

**Comment by bwiernik** [comment]
Broadly though, I don't understand when one would ever use \citetitle

**Comment by bdarcus** [comment]
> Broadly though, I don't understand when one would ever use \citetitle

I don't really either. :-)

But I know people, I think more in the humanities, use it for the same reason they want to only print the author. :shrug: 

Maybe we can see what @andras-simonyi concludes about this after he has a chance to work on it some more.

**Comment by andras-simonyi** [comment]
FYI, I've implemented the citation variants `textual`, `author-only`, `year-only` and `suppress-author` in the [15-citation_substyles](https://github.com/andras-simonyi/citeproc-el/tree/15-citation_substyles) branch, plus, as an extra, the branch also implements the `ignore-et-al` option requested in #16.

**Comment by bdarcus** [comment]
Great news @andras-simonyi!

> ... the next step will be making these new variants avaliable in org-cite.

I guess that will require a patch to oc-csl?

**Comment by andras-simonyi** [comment]
> Great news @andras-simonyi!
> 
> > ... the next step will be making these new variants avaliable in org-cite.
> 
> I guess that will require a small patch to oc-csl?

Yes, this is what I'm looking into right now. Meanwhile I noticed a terminological issue which I would like to ask you about: Currently I call `textual` `author` etc. variants in the code, but I noticed that Nicolas and you call these "styles", and refer to the optional `capitalized`, `bare`, `full-author-list` etc. as variants. I'd like to use standard terminology as far as possible but am a bit worried that talking about `citation styles` in this context will conflate these with CSL styles like chicago-author-date. Maybe `substyle` would be an acceptable solution? biblatex's `command` is also an option, but I feel it'd be a bit out of place outside LaTeX.

**Comment by bdarcus** [comment]
> Currently I call `textual` `author` etc. variants in the code and in the API, but I noticed that Nicolas and you call these "styles", and refer to the optional `capitalized`, `bare`, `full-author-list` etc. as variants. I'd like to use standard terminology as far as possible but am a bit worried that talking about `citation styles` in this context will conflate these with CSL styles. Maybe `substyle` would be an acceptable solution? 

That would probably be fine.

The `oc.el` code uses "variants", so you can keep that.

Maybe you do something like:

> Substyles (called "styles" in org-cite)

**Comment by andras-simonyi** [comment]
Thanks, I went with the `substyle` solution.

**Comment by bwiernik** [comment]
In CSL, we have referred to these as "commands" or "modes"

**Comment by bdarcus** [comment]
> In CSL, we have referred to these as "commands" or "modes"

I hadn't remembered that, but that's an option too, and has the advantage of it being consistent with the TeX world.

**Comment by andras-simonyi** [comment]
> In CSL, we have referred to these as "commands" or "modes"

Thanks, perhaps this has been the best suggestion so far so I've switched the code to it.

**Comment by bdarcus** [comment]
Are you planning to support OC "variants", and if so, how?

I'd guess you could keep that name for them if you do?

**Comment by andras-simonyi** [comment]
Those are binary switches in the citation constructor so fortunately I don't  have a similar terminological problem. To copy the docstring, this is what is supported now: 

MODE is either nil (for the default citation mode) or one
  of the symbols `suppress-author', `textual', `author-only',
  `year-only',
SUPPRESS-AFFIXES is non-nil if the citation affixes should be
  suppressed,
CAPITALIZE-FIRST is non-nil if the first word of the rendered
  citation should be capitalized,
IGNORE-ET-AL is non-nil if et-al settings should be ignored for
  the first cite.

**Comment by andras-simonyi** [comment]
OK, now I have a patched version of oc-csl which (seems to :-) ) support the new additions -- I'd be grateful if you could test it. What would be the most convenient way of posting it? a GitHub gist? or should I post a patch somewhere? (I guess I'll propose an official patch eventually on the mailing list but the citeproc-el features it relies on haven't even been merged into citeproc-el's master...)

**Comment by bdarcus** [comment]
Probably a gist.

**Comment by andras-simonyi** [comment]
thanks, here it is: https://gist.github.com/andras-simonyi/c79865da0b3252199b55d093f5a4ad64
an unintended but positive side effect (on my system) is that now the csl activation processor I wrote also formats the renderings according to the mode and variant information

**Comment by andras-simonyi** [comment]
there was a typo (a stray extra apostrophe) in the code, I've corrected it now

**Comment by bdarcus** [comment]
I checked out and compiled the branch, then opened `oc-csl.el` and compiled and loaded it.

But I got this:

``` console
cond: Keyword argument :mode not one of (:cites :note-index :capitalize-first :suppress-affixes :grouped)
```

... I am assuming the problem is on my end, but will just note it in case.

**Comment by bdarcus** [comment]
Just looking at the oc-csl code, minor thing: you need to update the commentary with the new styles.

**Comment by andras-simonyi** [comment]
> I checked out and compiled the branch, then opened `oc-csl.el` and compiled and loaded it.
> 
> But I got this:
> 
> ```
> cond: Keyword argument :mode not one of (:cites :note-index :capitalize-first :suppress-affixes :grouped)
> ```
> 
> ... I am assuming the problem is on my end, but will just note it in case.

strange -- looks like your Emacs still isn't using the feature branch's definition of `citeproc-citation-create` in citeproc-cite.el. Maybe you could manually check what the source contains, it should have the signature 

   citeproc-citation-create (&key cites note-index mode suppress-affixes capitalize-first ignore-et-al grouped)

**Comment by bdarcus** [comment]
I got it running now, but am not seeing any impact of the styles.

Here's my input:

```org

[cite/text:@test1]

[cite/author:@test1]

[cite/t:@test1]

[cite/a:@test1]
```

output:

```

(Low 2001)

(Low 2001)

(Low 2001)

(Low 2001)
```

But as always, it could be something with my install.

**Comment by andras-simonyi** [comment]
Well, I get the output below. FYI, I've merged now the branch, you can use the (up-to-date) master now and the version should also land in MELPA in a few hours.

```
Low (2001)

Low

Low (2001)

Low
```

**Comment by bdarcus** [comment]
That works now!

I'll test oc-csl more thoroughly today and get back to you.

**Comment by bdarcus** [comment]
Styles vs variants is incorrect here:

```elisp
(org-cite-supported-styles '(csl))
((("author" "a")
  ("caps" "c")
  ("bare-caps" "bc")
  ("bare" "b")
  ("noauthor" "na")
  ("year" "y"))
 (("nil")
  ("caps-full" "cf")
  ("text" "t")
  ("full" "f")
  ("caps" "c")
  ("bare-caps" "bc")
  ("bare" "b")))
```

**Comment by andras-simonyi** [comment]
> Styles vs variants is incorrect here:
> 
> ```emacs-lisp
> (org-cite-supported-styles '(csl))
> ((("author" "a")
>   ("caps" "c")
>   ("bare-caps" "bc")
>   ("bare" "b")
>   ("noauthor" "na")
>   ("year" "y"))
>  (("nil")
>   ("caps-full" "cf")
>   ("text" "t")
>   ("full" "f")
>   ("caps" "c")
>   ("bare-caps" "bc")
>   ("bare" "b")))
> ```

Thanks, good catch! Will double-check these registrations because they don't affect the export directly but I'm sure can bite elsewhere (e.g., with insertion).

**Comment by bdarcus** [comment]
These all look good:

```elisp
[cite/a:@test1]

[cite/y:@test1]

[cite/na:@test1]

[cite/t/f:@test1]

[cite/t/c:@test2]

[cite/t/cf:@test1]

[cite//b:@test1]
```

**Comment by andras-simonyi** [comment]
I've corrected the (org-cite-supported-styles '(csl)) problem, updated the gist as well.

**Comment by bdarcus** [comment]
I don't think this is a bug in the data, but try this:

``` elisp
[cite/t:@test3;@test1;@test2]
```

https://gist.github.com/bdarcus/4001a74161d1b1eba4617eccee1c14e0

I get this error:

```console
citeproc-cite--render: Wrong type argument: citeproc-itemdata, nil
```

Trying to test [this case](https://github.com/andras-simonyi/citeproc-el/issues/15#issuecomment-879276145).

**Comment by bdarcus** [comment]
> I've fixed the (org-cite-supported-styles '(csl)) issue

I still don't think the return value is right.

Compare to natbib.

**Comment by andras-simonyi** [comment]
> > I've fixed the (org-cite-supported-styles '(csl)) issue
> 
> I still don't think the return value is right.
> 
> Compare to natbib.

You are absolutely correct, I misread the logic. Fixed now, I think (in the gist as well).

**Comment by andras-simonyi** [comment]
> I don't think this is a bug in the data, but try this:
> 
> ```emacs-lisp
> [cite/t:@test3;@test1;@test2]
> ```
> 
> https://gist.github.com/bdarcus/4001a74161d1b1eba4617eccee1c14e0
> 
> I get this error:
> 
> ```
> citeproc-cite--render: Wrong type argument: citeproc-itemdata, nil
> ```
> 
> Trying to test [this case](https://github.com/andras-simonyi/citeproc-el/issues/15#issuecomment-879276145).

Thanks, looks like a genuine bug, I have to investigate.

**Comment by bdarcus** [comment]
So on the style lists, I'm wanting to write a function that presents the list of (correct) styles, but also includes a preview of the result.

https://github.com/bdarcus/bibtex-actions/issues/168

Do you know of a clever way to do this that would work across processors?

I'm hoping to do a POC today, as an alternative to another approach that I want to discourage :-)

**Comment by andras-simonyi** [comment]
> So on the style lists, I'm wanting to write a function that presents the list of (correct) styles, but also includes a preview of the result.
> Do you know of a clever way to do this that would work across processors?
> 
> Like, could I use `org-cite-export-citation` to export a dummy/example citation?

Depends on what you mean by "a preview  of the result".  Would the ensuing LaTeX citation command be an acceptable preview for the LaTeX processors? Or should the citation be rendered by LaTeX? For the CSL processor, on the other hand, it seems absolutely doable to provide a rendered preview as it is done by the CSL activation processor.

**Comment by bdarcus** [comment]
> Depends on what you mean by "a preview of the result".

Moved this sub-thread to https://github.com/bdarcus/bibtex-actions/issues/168#issuecomment-882046878.

**Comment by andras-simonyi** [comment]
> I don't think this is a bug in the data, but try this:
> 
> ```emacs-lisp
> [cite/t:@test3;@test1;@test2]
> ```
> 
> https://gist.github.com/bdarcus/4001a74161d1b1eba4617eccee1c14e0
> 
> I get this error:
> 
> ```
> citeproc-cite--render: Wrong type argument: citeproc-itemdata, nil
> ```
> 
> Trying to test [this case](https://github.com/andras-simonyi/citeproc-el/issues/15#issuecomment-879276145).

Hopefully fixed by commit cdb195e6e41be551c1714eb3b90c1cd047bca432 on master, I'd appreciate if you could test it.

**Comment by bdarcus** [comment]
> I'd appreciate if you could test it.

Quick test works as expected!

**Comment by andras-simonyi** [comment]
BTW, when patching `oc-csl.el` to support the new modes and variants I was unsure how many variant-combinations should be supported for the specific modes, and excluded some combinations with seemingly no sensible use. E.g., it doesn's seem to make much sense to use the `full` variant with the default/nil styles, but who knows? Another strategy would be to support all possible combinations. WDYT?

**Comment by bdarcus** [comment]
I think reasonable defaults are good.

You can always add more later if people request?

**Comment by andras-simonyi** [comment]
Closing this as the corresponding feature branch has been merged into master (see #29).

**Comment by bdarcus** [comment]
One question that just occurred to on this:

> [cite/t:@test3;@test1;@test2]

How do you handle knowing where to put any affixes when grouping and sorting?

E.g. this:

> [cite/t:@test2;@test3; see also @test1]

Or more precisely, what's the recommendation for users? To be aware of this?

**Comment by andras-simonyi** [comment]
Good question! On solution I can think of is the kind of instant preview now provided by `org-cite-csl-activate` if the used style is the export style then the user will immediately see whether a reordering is a problem. A different type of solution could be not to reorder when affixes are specified.

**Comment by bdarcus** [comment]
I think I like the first option better, as visualization is really the
primary problem.

**Comment by bwiernik** [comment]
This is a thing that pandoc has some struggles with too. It would be nice if pandoc and orgcite had the same syntax

**Comment by bdarcus** [comment]
> This is a thing that pandoc has some struggles with too. It would be nice if pandoc and orgcite had the same syntax

There a couple of improvements in org-cite over pandoc, but it comes at the cost of some verbosity, which is more manageable in org-mode.
